# Running the Flask app
run:
    uv run flask --app spoteezer.flask_app:app run

# Testing
test:
    uv run pytest

# Linting
lint:
    uv run ruff check . --fix

# Type checking
type:
    uv run ty check
